# Generated by Django 4.2.3 on 2023-07-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='administrator',
            managers=[
            ],
        ),
    ]
