# Generated by Django 4.2.3 on 2023-08-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_headquarters_physical_address',
            field=models.CharField(default='abc', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_jurisdiction',
            field=models.CharField(default='abc', max_length=400),
            preserve_default=False,
        ),
    ]
