# Generated by Django 4.2.3 on 2023-08-09 15:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_website',
            field=models.CharField(max_length=255, unique=True, validators=[api.models.full_domain_validator]),
        ),
    ]
