# Generated by Django 4.2.3 on 2023-07-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_administrator_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='company_address',
            field=models.TextField(default='softy', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrator',
            name='company_name',
            field=models.CharField(default='softy', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrator',
            name='company_size',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrator',
            name='industry',
            field=models.CharField(default='product', max_length=50),
            preserve_default=False,
        ),
    ]
