# Generated by Django 4.2.3 on 2023-08-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_headquarters_physical_address',
            field=models.CharField(default='abc', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_jurisdiction',
            field=models.CharField(default='abc', max_length=400),
            preserve_default=False,
        ),
    ]
