# Generated by Django 4.2.3 on 2023-07-18 15:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_administrator_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='company_address',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='company_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='industry',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
