# Generated by Django 4.2.3 on 2023-08-21 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_company_headquarters_physical_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_headquarters_physical_address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_unique_identifier',
            field=models.FileField(blank=True, null=True, upload_to='company_identifiers/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
