# Generated by Django 4.2.3 on 2023-08-23 17:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_administrator_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identifier', models.CharField(max_length=25, unique=True)),
                ('unique_identifier_type', models.CharField(choices=[('SKU', 'Sku'), ('GNIT', 'Gnit')], max_length=4)),
                ('marketing_name', models.CharField(max_length=500)),
                ('version', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('state', models.CharField(choices=[('Draft', 'Draft'), ('Pubished', 'Published'), ('Hidden', 'Hidden')], max_length=8)),
                ('sctr_cogs', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='SourceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction_cogs', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('marketing_name', models.CharField(max_length=500)),
                ('component_type', models.CharField(choices=[('Externally Sourced', 'Externally Sourced'), ('Made In-House', 'Made In House')], max_length=18)),
                ('country_of_origin', django_countries.fields.CountryField(max_length=2, null=True)),
                ('external_sku', models.CharField(max_length=25, null=True)),
                ('parent_sctr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sctr')),
            ],
        ),
        migrations.RemoveField(
            model_name='subcomponent',
            name='main_sku_id',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SubComponent',
        ),
    ]
