# Generated by Django 4.2.3 on 2023-08-28 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sourcecomponent_parent_sctr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sctr',
            name='marketing_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sctr',
            name='sctr_cogs',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sctr',
            name='state',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pubished', 'Published'), ('Hidden', 'Hidden')], default='Draft', max_length=8),
        ),
        migrations.AlterField(
            model_name='sctr',
            name='unique_identifier_type',
            field=models.CharField(choices=[('SKU', 'Sku'), ('GNIT', 'Gnit')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='sourcecomponent',
            name='component_type',
            field=models.CharField(choices=[('Externally Sourced', 'Externally Sourced'), ('Made In-House', 'Made In House')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='sourcecomponent',
            name='marketing_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sourcecomponent',
            name='fraction_cogs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
