# Generated by Django 4.2.3 on 2023-08-30 15:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_sctr_marketing_name_alter_sctr_sctr_cogs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sctr',
            old_name='sctr_cogs',
            new_name='cogs',
        ),
        migrations.AlterField(
            model_name='sctr',
            name='state',
            field=models.IntegerField(choices=[(1, 'DRAFT'), (2, 'PUBLISHED'), (3, 'HIDDEN')], default=api.models.SCTR_STATES['DRAFT']),
        ),
        migrations.AlterField(
            model_name='sctr',
            name='unique_identifier_type',
            field=models.IntegerField(choices=[(1, 'SKU'), (2, 'GNIT')], null=True),
        ),
        migrations.AlterField(
            model_name='sourcecomponent',
            name='component_type',
            field=models.IntegerField(choices=[(1, 'EXTERNALLY_SOURCED'), (2, 'MADE_IN_HOUSE')], null=True),
        ),
    ]
