# Generated by Django 4.2.4 on 2023-09-01 19:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_sctr_unique_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sctr',
            name='unique_identifier_type',
            field=models.IntegerField(choices=[(1, 'SKU'), (2, 'GNIT')], default=api.models.ORIGIN_REPORT_ID_TYPES['SKU']),
        ),
    ]
