# Generated by Django 4.2.4 on 2023-09-11 15:31

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_sctr_is_latest_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecomponent',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sctr',
            name='version',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
