# Generated by Django 4.2.5 on 2023-09-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_sourcecomponent_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "alpha_2",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("alpha_3", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("official_name", models.CharField(max_length=255, unique=True)),
                ("free", models.BooleanField()),
            ],
        ),
    ]
