# Generated by Django 4.2.5 on 2023-09-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_country_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecomponent',
            name='country_of_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country'),
        ),
    ]
