# Generated by Django 4.2.5 on 2023-09-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_sourcecomponent_country_of_origin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="originreport",
            old_name="marketing_name",
            new_name="short_description",
        ),
        migrations.RenameField(
            model_name="sourcecomponent",
            old_name="marketing_name",
            new_name="short_description",
        ),
    ]
