# Generated by Django 4.2.3 on 2023-09-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_marketing_name_originreport_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to='company_logo/'),
        ),
    ]
