# Generated by Django 4.2.5 on 2023-09-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='originreport',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='origin_report_thumbnail/'),
        ),
    ]
