version: 2
updates:

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
      include: "scope"
    assignees:
      - "bakerkj"
    reviewers:
      - "guilsuper"
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      patch:
        update-types:
          - "patch"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "pip"
      include: "scope"
    assignees:
      - "bakerkj"
    reviewers:
      - "bakerkj"
    groups:
      patch:
        update-types:
          - "patch"
    open-pull-requests-limit: 10

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    assignees:
      - "bakerkj"
    reviewers:
      - "bakerkj"
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10

  # Maintain dependencies for e2e-tests pip
  - package-ecosystem: "pip"
    directory: "/e2e-tests"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "e2e-tests pip"
      include: "scope"
    assignees:
      - "bakerkj"
    reviewers:
      - "bakerkj"
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10

  # Maintain dependencies for backend docker
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker backend"
      include: "scope"
    assignees:
      - "bakerkj"
    reviewers:
      - "bakerkj"
    open-pull-requests-limit: 10

  # Maintain dependencies for frontend docker
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker frontend"
      include: "scope"
    assignees:
      - "bakerkj"
    reviewers:
      - "bakerkj"
    open-pull-requests-limit: 10

  # Maintain dependencies for e2e-tests docker
  - package-ecosystem: "docker"
    directory: "/e2e-tests"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker e2e-tests"
      include: "scope"
    assignees:
      - "bakerkj"
    reviewers:
      - "bakerkj"
    open-pull-requests-limit: 10

  # Maintain dependencies for e2e-tests/sendgrid-mock docker
  - package-ecosystem: "docker"
    directory: "/e2e-tests/sendgrid-mock"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker e2e-tests/sendgrid-mock"
      include: "scope"
    assignees:
      - "bakerkj"
    reviewers:
      - "bakerkj"
    open-pull-requests-limit: 10

  # Maintain dependencies for e2e-tests/selenium docker
  - package-ecosystem: "docker"
    directory: "/e2e-tests/selenium"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker e2e-tests/selenium"
      include: "scope"
    assignees:
      - "bakerkj"
    reviewers:
      - "bakerkj"
    open-pull-requests-limit: 10

  # Maintain dependencies for terraform
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "terraform"
      include: "scope"
    assignees:
      - "bakerkj"
    reviewers:
      - "bakerkj"
    open-pull-requests-limit: 10
