repos:
  - repo: local
    hooks:
    - id: flake8
      name: flake8
      entry: flake8 --config=.flake8
      exclude: migrations
      language: python
      additional_dependencies: [
        flake8-docstrings,
        flake8-import-order,
        flake8-quotes,
      ]
