repos:
  - repo: local
    hooks:
    - id: flake8
      name: flake8
      entry: flake8 --config=.flake8

      # Flake doesn't ignore these folders by itself
      exclude: "(migrations|templates)/.*"

      language: python

      types: [
        python,
      ]
      
      additional_dependencies: [
        flake8-docstrings,
        flake8-import-order,
        flake8-quotes,
      ]
