repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.3
    hooks:
      - id: remove-crlf
      - id: forbid-tabs

  - repo: https://github.com/iamthefij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch

      - id: check-docstring-first

      - id: check-executables-have-shebangs

      - id: check-shebang-scripts-are-executable

      - id: pretty-format-json
        exclude: "(frontend/package-lock.json)"
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]

      - id: check-json

      - id: check-merge-conflict

      - id: check-yaml

      - id: end-of-file-fixer

      - id: mixed-line-ending
        args: [ --fix=lf ]

      - id: requirements-txt-fixer

      - id: trailing-whitespace

      - id: check-added-large-files

  - repo: https://github.com/sirosen/texthooks
    rev: 0.5.0
    hooks:
      - id: fix-smartquotes
      - id: fix-spaces

  - repo: https://github.com/pre-commit/mirrors-csslint
    rev: v1.0.5
    hooks:
      - id: csslint

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.3
    hooks:
      - name: Insert license in comments (.js|.css)
        id: insert-license
        files: \.(js|css)$
        args:
          - --use-current-year
          - --comment-style
          - /*| *| */
      - name: Insert license in comments (.py)
        id: insert-license
        files: \.(py)$
        exclude: "(backend/api/migrations/)"
        args:
          - --use-current-year
          - --no-extra-eol
      - name: Insert license in comments (.sh)
        id: insert-license
        files: \.(sh)$
        args:
          - --use-current-year

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-1
    hooks:
      - id: shfmt

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports
        args: [ --py39-plus, ]
        exclude: "(backend/api/migrations/)"

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        args: [ --fix ]

  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.6
    hooks:
      - id: ripsecrets

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        exclude: frontend/package.lock.json

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        exclude: "(frontend/package-lock.json)"

  - repo: https://github.com/crate-ci/typos
    rev: v1.16.17
    hooks:
      - id: typos
        exclude: "(backend/api/migrations/|example-data/products.yaml|backend/free_world_countries/.*.csv|frontend/public/locales/[a-z]{2}/translation.json)"

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.3
    hooks:
      - id: check-github-workflows
      - id: check-dependabot

  - repo: https://github.com/aquasecurity/tfsec.git
    rev: v1.28.1
    hooks:
      - id: tfsec

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: flake8

        # Flake doesn't ignore these folders by itself
        exclude: "(migrations)/.*"

        additional_dependencies:
          - flake8-quotes

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.46.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.50.0
          - eslint-config-standard@^17.1.0
          - eslint-plugin-i18next@^6.0.3
          - eslint-plugin-import@^2.28.1
          - eslint-plugin-jest@^27.4.2
          - eslint-plugin-n@^16.1.0
          - eslint-plugin-promise@^6.1.1
          - eslint-plugin-react@^7.33.2
          - jest@^29.6.4
        args: [ --fix, --ignore-pattern, node_modules, ]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.82.0
    hooks:
      - id: terraform_fmt
