services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - prod-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10

  sendgrid-mock:
    build:
      context: ./e2e-tests/sendgrid-mock/
      dockerfile: Dockerfile
    environment:
      - API_KEY=SENDGRID_MOCK_KEY
    ports:
      - "3001:3000"
    networks:
      - prod-net
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 5s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/backend
      - media:/backend/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DATABASE=production
      - DJANGO_SETTINGS_MODULE=product.settings.development_settings
      - DEBUG=False
      - ALLOWED_HOST=backend
      - SENDGRID_HOST=http://sendgrid-mock:3000
      - SENDGRID_API_KEY=SENDGRID_MOCK_KEY
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      sendgrid-mock:
        condition: service_healthy
    networks:
      - prod-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-nginx
    ports:
      - '3000:3000'
    volumes:
      - ./e2e-tests/nginx/templates:/etc/nginx/templates
      - media:/usr/share/nginx/media
    environment:
      - BACKEND_HOST=http://backend:8000
    networks:
      - prod-net
    depends_on:
      - backend

networks:
  prod-net:
    driver: bridge

volumes:
  media:
