services:
  e2e-tests:
    build:
      context: ./e2e-tests
      dockerfile: Dockerfile
    volumes:
      - ./e2e-tests:/e2e-tests
      - ./test-results:/test-results
    environment:
      - FRONTEND=http://frontend:3000
      - BACKEND=http://backend:8000
      - SENDGRID_HOST=http://sendgrid-mock:3000
      - SELENIUM_HOST=http://selenium-chrome:4444
    depends_on:
      selenium-chrome:
        condition: service_healthy
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
      sendgrid-mock:
        condition: service_healthy
    networks:
      - prod-net

  selenium-chrome:
    build:
      context: ./e2e-tests/selenium/
      dockerfile: Dockerfile
    networks:
      - prod-net
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      SE_OPTS: "--log-level WARNING"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444"]
      interval: 5s
      timeout: 10s
      retries: 10

  db-test:
    image: postgres
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - prod-net

  sendgrid-mock:
    build:
      context: ./e2e-tests/sendgrid-mock/
      dockerfile: Dockerfile
    environment:
      - API_KEY=SENDGRID_MOCK_KEY
    ports:
      - "3001:3000"
    networks:
      - prod-net
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 5s
      timeout: 10s
      retries: 10

  # By default, cleanup media volume
  media-volume-cleanup:
    build:
      context: ./e2e-tests/media-volume-cleanup
      dockerfile: Dockerfile
    volumes:
      - media:/mnt/media

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/backend
      - media:/backend/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False

      - ALLOWED_HOST=backend
      - FRONTEND_HOST=http://localhost:3000

      - DJANGO_DATABASE=production
      - DJANGO_SETTINGS_MODULE=product.settings.e2e_test_settings
      - SECRET_KEY='8_*lw4(^907@enln%2r(av@__8_$w46n-h+s7s_7lm%ar5c_e6'

      - POSTGRES_HOST=db-test
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432

      - SENDGRID_HOST=http://sendgrid-mock:3000
      - SENDGRID_API_KEY=SENDGRID_MOCK_KEY
    depends_on:
      media-volume-cleanup:
        condition: service_started
      db-test:
        condition: service_healthy
      sendgrid-mock:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8000/api/"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - prod-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./e2e-tests/nginx/templates:/etc/nginx/templates
      - media:/usr/share/nginx/media
    environment:
      - BACKEND_HOST=http://backend:8000
    networks:
      - prod-net
    depends_on:
      media-volume-cleanup:
        condition: service_started
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 1s
      timeout: 2s
      retries: 10

networks:
  prod-net:
    driver: bridge

volumes:
  media:
