repos:
  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
    - id: flake8
      exclude: migrations
      args:
        ["--config=.flake8"]
      additional_dependencies: [
        flake8-docstrings,
        flake8-import-order,
        flake8-quotes,
      ]
