

FWC Data Schema Version: 0.1

Companies:
  - LegalName: Acme Manufacturer
    PrimaryDomain: acme-manufacturer.com
    PrimaryDomainVerified: true
    HeadquartersCountry: USA
    JurisdictionOfIncorporation: Delaware, USA
    Products:
      - ProductName: Waffle Iron #8
        SKU: TheWaffler8
        OriginReports:
          Versions:
          - Version: 1
            PublicationDate: 2023-08-21T01:23:45Z
            Inputs:
            - FractionCOGS: 0.2
              Type: In-House
              Description: Iron Bar Stock
              Origin: USA
            - FractionCOGS: 0.8
              Type: In-House
              Description: Forging of iron
              Origin: USA
          - Version: 2
            PublicationDate: 2023-08-31T01:23:45Z
            Inputs:
            - FractionCOGS: 0.3
              Type: In-House
              Description: Iron Bar Stock
              Origin: USA
            - Fraction COGS: 0.7
              Type: In-House
              Description: Forging of iron
              Origin: Canada

      - ProductName: Frying Pan #12
        SKU: TheFryer12
        OriginReports:
          Versions:
          - Version: 1
            PublicationDate: 2023-08-29T01:23:45Z
            Inputs:
            - FractionCOGS: 0.7
              Type: In-House
              Description: Forging of iron
              Origin: USA
              PublicationDate: 2023-08-31T01:23:45Z
          - Version: 2
            PublicationDate: 2023-08-31T23:23:45Z
            Inputs:
            - FractionCOGS: 0.3
              Type: External
              Description: Fancy iron bar stock
              Supplier:
                Status: Guess
                Origin: Zimbabwe
                SKU: ultra-manganese-707
                LegalName: Excellent Zimbabwe, Ltd
                PrimaryDomain: fancy-iron.ze
                HeadquartersCountry: Zimbabwe
                JurisdictionOfIncorporation: Harare, Zimbabwe


  - LegalName: Essentia Mattresses
    PrimaryDomain: myessentia.ca
    PrimaryDomainVerified: true
    HeadquartersCountry: Canada
    JurisdictionOfIncorporation: Canada
    Products:
      - ProductName: Opus Energie, Queen
        SKU: 12348u9128u4
        Origin Reports:
          Versions:
          - Version: 1
            Publication Date: 2023-08-22T01:01:01Z
            Inputs:
            - FractionCOGS: 70%
              Type: In-House
              Description: Labor for Assembly
              Origin: Malaysia
            - FractionCOGS: 30%
              Type: External
              Description: Raw Latex
              Supplier:
                Status: Certified
                PrimaryDomain: best-latex.br
                SKU: latex-100-pure



  - LegalName: Best Latex, Inc.
    PrimaryDomain: best-latex.br
    PrimaryDomainVerified: true
    Headquarters Country: Brazil            # key into the list of countries
    Jurisdiction of Incorporation: Brazil   # key into the list of countries
    Products:
      - ProductName: Wonderful Latex
        SKU: latex-100-pure
        OriginReprots:
          Versions:
          - Version: 1
            PublicationDate: 2023-08-22T01:01:01Z
            Inputs:
            - FractionCOGS: 80%
              Type: In-House
              Description: Latex
              Origin: Brazil
            - FractionCOGS: 20%
              Type: External
              Description: Solvents
              Supplier:
                Status: Guess
                Origin: USA
                SKU: toluene
                LegalName: DuPont, Inc
                PrimaryDomain: DuPont.com
                HeadquartersCountry: USA
                JurisdictionOfIncorporation: USA
